# Generated by Django 2.2.5 on 2019-09-19 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('secret', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ensure the SDI name has not been used before.', max_length=255, unique=True, verbose_name='LTI SDI Name')),
                ('sdios_environment_uuid', models.CharField(max_length=36, unique=True)),
                ('lti_environment_key', models.CharField(max_length=255, unique=True, verbose_name='LTI SDI Key')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdios_url', models.CharField(default='127.0.0.1:8000', help_text='This is where your SDI OS instance lives.', max_length=255, verbose_name=' URL')),
                ('sdios_username', models.CharField(default='', help_text='The username of your SDI OS API user.', max_length=255, verbose_name='SDI OS API username')),
                ('sdios_password', models.CharField(default='', help_text='The password of your SDI OS API user.', max_length=255, verbose_name='SDI OS API password')),
                ('client_id', models.CharField(default='', help_text='Client ID found under API application at {SDI OS URL}/api/o/applications.', max_length=255, verbose_name='Client ID')),
                ('client_secret', models.CharField(default='', help_text='Client Secret found under API application at {SDI OS URL}/api/o/applications.', max_length=255, verbose_name='Client Secret')),
            ],
        ),
        migrations.CreateModel(
            name='UserMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lti_user_id', models.CharField(max_length=255)),
                ('sdios_username', models.CharField(max_length=255, unique=True)),
                ('sdios_password', models.CharField(max_length=255)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdios_lti.Consumer')),
            ],
            options={
                'unique_together': {('consumer', 'lti_user_id')},
            },
        ),
    ]
